### ISSUE TITLE
Доказательство условия сходимости ряда Фурье в точке

### ISSUE THREAD

**Issue by Pr0f1D0c** [dainbow/GarmanMIPT#10]
https://github.com/dainbow/GarmanMIPT/blob/eef6415cd74c300e40fb28dac7c2154bbc719a66/main.tex#L329

1. Откуда взялось третье слагаемое? Кажется, что sin(nt) \cdot ctg(t/2) / 2 уже присутствует в четвертом слагаемом, а "добавим-вычтем" с ним не производилось, в отличии от sin(nt) / t, что, кажется, лучше явно прописать.
2. В доказательстве устранимости разрыва ошибочно написано t \to \infty: разрыв исследуется в нуле

**Comment by Pr0f1D0c** [comment]
UPD: с первым пунктом понял, не заметил пределов интегрирования. Лучше тоже это, наверное, прописать явно, а то не заметно, что интеграл разбивается на две части..

**Comment by dainbow** [comment]
Исправил в f454a34
1. Добавил уточнение
2. Пофиксил
