### ISSUE TITLE
Теорема 4.2

### ISSUE THREAD

**Issue by Pr0f1D0c** [dainbow/GarmanMIPT#11]
https://github.com/dainbow/GarmanMIPT/blob/f454a34408cc8637be6effcc7fb34172a3ef8986/main.tex#L423

пропущен косинус

**Comment by dainbow** [comment]
Мы здесь неравенство пишем, поэтому косинус оценили 1 сверху сразу, но это надо уточнить. Пофиксил в 7e0e3b3
