### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by IraZhulyabina** [dainbow/GarmanMIPT#8]
https://github.com/dainbow/GarmanMIPT/blob/057e3649d22a55d830914d702739553d5023c664/main.tex#L161

Здесь g:=f\mathbb{I}_{[-N-1,\,N+1]}

**Comment by dainbow** [comment]
![image](https://github.com/dainbow/GarmanMIPT/assets/26509840/717f1de0-a05e-45a1-ad4b-38218c7c00c5)
Неа, у Лукашова в лекции так и было
