### ISSUE TITLE
Mistake

### ISSUE THREAD

**Issue by IraZhulyabina** [dainbow/GarmanMIPT#9]
https://github.com/dainbow/GarmanMIPT/blob/057e3649d22a55d830914d702739553d5023c664/main.tex#L411

Здесь ещё нужна 2\pi периодичность f(x), чтобы мы могли сдвигать переменные на \pi/n без замены промежутка интегрирования

**Comment by dainbow** [comment]
Согласен, пофикшено в 8cb2efc
